### ISSUE TITLE
Adapting for mobile in real time

### ISSUE THREAD

**Issue by myketheguru** [lewisExternal/BillboardAdvertDetection#1]
Hello @lewisExternal 

I went through the blog post and I must say, it's pretty impressive.  Thanks for putting in the work on this one. This issue is really just me seeking advice.

I'm building an app that is supposed to track billboards and signs in real time and return their estimated measurements (Dimension: Width/Height). How could I adapt your solution to train a model that does this?

I'd really appreciate your response

**Comment by lewisExternal** [comment]
Hi @myketheguru 

Thanks for your question, glad you liked the project! 

It's an interesting question and should make for an interesting project, I had a look online as I am not too familiar with this use case. 

The closest solution I'd be inclined to investigate would be something like the below.
https://pyimagesearch.com/2016/03/28/measuring-size-of-objects-in-an-image-with-opencv/ 

Failing that, I think I'd look into the Photogrammetry academic literature as it seems the task is of reasonable complexity.  

Hope this helps.

**Comment by myketheguru** [comment]
Thank you so much for your response @lewisExternal 

I have gone through the article, and it is indeed quite close. I will try to incorporate and translate the solution in react native.

There's an issue related to the project though, after mounting it on docker and running it, whenever I try to search for anything, I get errors related to chrome driver.

```
UnboundLocalError: local variable 'driver' referenced before assignment
Traceback:
File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "/src/main.py", line 119, in <module>
    app()
File "/src/main.py", line 92, in app
    st.session_state['image_urls_df'] = image_search_using_selenium()
File "/src/main.py", line 70, in image_search_using_selenium
    driver.quit()
```

I did try to modify the code but wasn't successful in narrowing down the error

**Comment by lewisExternal** [comment]
Seems to have been an out of date version of the undetected chromedriver package. 

Pull the latest from master and this should now be fixed.
